# Generated by Django 5.0.1 on 2026-09-24 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_short_rest_price', models.DecimalField(decimal_places=2, default=8000.0, max_digits=10)),
                ('short_rest_duration_hours', models.IntegerField(default=2)),
                ('short_rest_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_base_price', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('default_short_rest_price', models.DecimalField(decimal_places=2, default=8000.0, max_digits=10)),
                ('capacity', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='is_short_rest_available',
            field=models.BooleanField(default=True, help_text='Designated for short rest'),
        ),
        migrations.AddField(
            model_name='room',
            name='short_rest_price',
            field=models.DecimalField(decimal_places=2, default=8000.0, help_text='Price for short rest', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
