# Generated by Django 5.2.4 on 2026-04-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_premium_product_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine'), ('spirit', 'Spirit'), ('soft_drink', 'Soft Drink'), ('juice', 'Juice'), ('cocktail', 'Cocktail'), ('champagne', 'Champagne'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('premium_spirit', 'Premium Spirit'), ('food', 'Food'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('pint', 'Pint'), ('glass', 'Glass'), ('can', 'Can'), ('shot', 'Shot'), ('cup', 'Cup'), ('plate', 'Plate'), ('piece', 'Piece'), ('unit', 'Unit')], default='unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
