# Generated by Django 5.0.1 on 2026-09-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_guest_email_alter_guest_last_name_and_more'),
        ('rooms', '0002_roomsettings_roomtypeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_number_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room'),
        ),
    ]
